// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TodoApi.Models;

namespace Asp_Api.Migrations
{
    [DbContext(typeof(TodoContext))]
    [Migration("20190415221821_comments")]
    partial class comments
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("TodoApi.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DateComment");

                    b.Property<string>("Message");

                    b.Property<int?>("PetLostPetId");

                    b.HasKey("CommentId");

                    b.HasIndex("PetLostPetId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("TodoApi.Models.PetLost", b =>
                {
                    b.Property<int>("PetId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DatePublish");

                    b.Property<string>("Description");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<string>("Picture");

                    b.Property<bool>("Status");

                    b.HasKey("PetId");

                    b.ToTable("PetLosts");
                });

            modelBuilder.Entity("TodoApi.Models.Comment", b =>
                {
                    b.HasOne("TodoApi.Models.PetLost", "PetLost")
                        .WithMany()
                        .HasForeignKey("PetLostPetId");
                });
#pragma warning restore 612, 618
        }
    }
}
